# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

admm_lambda_seq <- function(x, y, weights, k, lambda, nlambda = 50L, lambda_max = -1.0, lambda_min = -1.0, lambda_min_ratio = 1e-5, max_iter = 200L, rho_scale = 1.0, tol = 1e-5, tridiag = FALSE) {
    .Call(`_trendfilter_admm_lambda_seq`, x, y, weights, k, lambda, nlambda, lambda_max, lambda_min, lambda_min_ratio, max_iter, rho_scale, tol, tridiag)
}

get_dk_mat <- function(k, xd, tf_weighting) {
    .Call(`_trendfilter_get_dk_mat`, k, xd, tf_weighting)
}

get_penalty_mat <- function(k, xd) {
    .Call(`_trendfilter_get_penalty_mat`, k, xd)
}

get_lambda_max <- function(x, y, weights, k) {
    .Call(`_trendfilter_get_lambda_max`, x, y, weights, k)
}

calc_degrees_of_freedom <- function(v, k, tol) {
    .Call(`_trendfilter_calc_degrees_of_freedom`, v, k, tol)
}

get_lambda_seq_r <- function(lambda, lambda_max, lambda_min, lambda_min_ratio, n_lambda) {
    .Call(`_trendfilter_get_lambda_seq_r`, lambda, lambda_max, lambda_min, lambda_min_ratio, n_lambda)
}

Dkv <- function(v, k, xd, tf_weighting) {
    .Call(`_trendfilter_Dkv`, v, k, xd, tf_weighting)
}

