# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

smat_to_mat <- function(sparseMat, k, equal_spaced) {
    .Call(`_trendfilter_smat_to_mat`, sparseMat, k, equal_spaced)
}

configure_denseD_test <- function(x, k) {
    .Call(`_trendfilter_configure_denseD_test`, x, k)
}

linear_single_solve_test <- function(linear_solver, y, weights, x, rho, adj_mean) {
    .Call(`_trendfilter_linear_single_solve_test`, linear_solver, y, weights, x, rho, adj_mean)
}

compute_P_matrix <- function(x_target, x_support) {
    .Call(`_trendfilter_compute_P_matrix`, x_target, x_support)
}

compute_C_withoutTheta <- function(x_support) {
    .Call(`_trendfilter_compute_C_withoutTheta`, x_support)
}

compute_A_matrix <- function(x_target, x_support) {
    .Call(`_trendfilter_compute_A_matrix`, x_target, x_support)
}

ns_matrix <- function(x, m1, m2) {
    .Call(`_trendfilter_ns_matrix`, x, m1, m2)
}

admm_lambda_seq <- function(x, y, weights, k, boundary_condition, left_boundary_m, right_boundary_m, lambda, nlambda = 50L, lambda_max = -1.0, lambda_min = -1.0, lambda_min_ratio = 1e-5, max_iter = 200L, rho_scale = 1.0, tol = 1e-5, linear_solver = 2L, space_tolerance_ratio = -1.0) {
    .Call(`_trendfilter_admm_lambda_seq`, x, y, weights, k, boundary_condition, left_boundary_m, right_boundary_m, lambda, nlambda, lambda_max, lambda_min, lambda_min_ratio, max_iter, rho_scale, tol, linear_solver, space_tolerance_ratio)
}

get_dk_mat <- function(k, xd, tf_weighting) {
    .Call(`_trendfilter_get_dk_mat`, k, xd, tf_weighting)
}

get_penalty_mat <- function(k, xd) {
    .Call(`_trendfilter_get_penalty_mat`, k, xd)
}

get_lambda_max <- function(x, y, weights, k) {
    .Call(`_trendfilter_get_lambda_max`, x, y, weights, k)
}

calc_degrees_of_freedom <- function(v, k, tol) {
    .Call(`_trendfilter_calc_degrees_of_freedom`, v, k, tol)
}

get_lambda_seq_r <- function(lambda, lambda_max, lambda_min, lambda_min_ratio, n_lambda) {
    .Call(`_trendfilter_get_lambda_seq_r`, lambda, lambda_max, lambda_min, lambda_min_ratio, n_lambda)
}

Dkv <- function(v, k, xd, tf_weighting) {
    .Call(`_trendfilter_Dkv`, v, k, xd, tf_weighting)
}

is_equal_space <- function(x, space_tolerance_ratio) {
    .Call(`_trendfilter_is_equal_space`, x, space_tolerance_ratio)
}

